import { spawn } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { lstat, readFile, rename, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import type { ExtensionAPI } from '@oh-my-pi/pi-coding-agent';
import { runCheck as defaultRunCheck } from '../runtime/ui-delivery/checks.ts';
import { appendEvidence } from '../runtime/ui-delivery/evidence.ts';
import { authorizePath } from '../runtime/ui-delivery/paths.ts';
import { authorizationDigest, candidateHash, loadTask, resolveTaskFile } from '../runtime/ui-delivery/task.ts';
import { createStitchPolicy, type StitchPolicy } from '../runtime/ui-delivery/stitch-policy.ts';

const STATUS = { extension: 'ui-delivery-policy', status: 'ready' } as const;
const result = (details: Record<string, unknown>) => ({ content: [{ type: 'text' as const, text: JSON.stringify(details) }], details });
function diffTargets(patch: string): string[] { const lines = patch.split('\n'); const targets: string[] = []; for (let index = 0; index < lines.length;) { if (!lines[index]) { index += 1; continue; } const header = /^diff --git a\/([^\s]+) b\/([^\s]+)$/.exec(lines[index++]); if (!header) throw new Error('unsafe or unparseable diff policy'); const [oldPath, newPath] = [header[1], header[2]]; if ([oldPath, newPath].some((path) => path.startsWith('/') || path.split('/').includes('..'))) throw new Error('unsafe diff path'); let created = false; if (/^new file mode 100644$/.test(lines[index])) { created = true; index += 1; if (!/^index 0{7,64}\.\.[0-9a-f]{7,}(?: 100644)?$/i.test(lines[index++])) throw new Error('malformed new-file metadata'); } else if (/^(?:new|old) mode|^(?:rename|copy) |^similarity index|^dissimilarity index|^Binary /.test(lines[index] ?? '')) throw new Error('destructive or symlink diff policy'); else if (/^index [0-9a-f]{7,}\.\.[0-9a-f]{7,}(?: 100644)?$/i.test(lines[index])) index += 1; if ((created && (oldPath !== newPath || lines[index++] !== '--- /dev/null' || lines[index++] !== `+++ b/${newPath}`)) || (!created && (oldPath !== newPath || lines[index++] !== `--- a/${oldPath}` || lines[index++] !== `+++ b/${newPath}`))) throw new Error('unsafe or destructive diff policy'); let hunks = 0; while (index < lines.length && !lines[index].startsWith('diff --git ')) { if (lines[index].startsWith('@@ ')) hunks += 1; else if (/^(?:new|old) mode|^(?:rename|copy) |^similarity index|^Binary |^(?:---|\+\+\+) /.test(lines[index])) throw new Error('malformed diff metadata'); index += 1; } if (!hunks || targets.includes(newPath)) throw new Error('unparseable diff policy'); targets.push(newPath); } if (!targets.length) throw new Error('patch has no file targets'); return targets; }
async function gitApply(cwd: string, patch: string, signal: AbortSignal): Promise<void> { const { promise, resolve, reject } = Promise.withResolvers<void>(); const child = spawn('git', ['apply', '--whitespace=nowarn', '--'], { cwd, shell: false, stdio: ['pipe', 'ignore', 'pipe'], signal }); let stderr = ''; child.stderr.on('data', (chunk) => { stderr += String(chunk).slice(0, 4096 - stderr.length); }); child.once('error', reject); child.once('close', (code) => code === 0 ? resolve() : reject(new Error(`git apply failed${stderr ? ': rejected patch' : ''}`))); child.stdin.end(patch); return promise; }
function exactResult(value: unknown): boolean { if (!value || typeof value !== 'object') return false; const entry = value as Record<string, unknown>; return entry.schema === 'ui-delivery-check-v1' && Number.isInteger(entry.required) && entry.required >= 1 && entry.passed === entry.required && entry.failed === 0 && entry.skipped === 0; }
async function outputPath(repo: string, task: any, checkId: string, path: string): Promise<string> { const recipe = task.approved_check_recipes.find((entry: any) => entry.id === checkId); if (!recipe?.write_paths?.includes(path)) throw new Error('artifact is not a declared check output'); return authorizePath({ repo, task: { allowed_paths: recipe.write_paths, forbidden_policy_paths: task.forbidden_policy_paths }, path }); }
async function freshArtifact(path: string, before?: { mtimeNs: bigint; size: number }): Promise<{ hash: string }> { const stat = await lstat(path, { bigint: true }); if (!stat.isFile() || stat.isSymbolicLink() || stat.nlink !== 1 || stat.size < 1n || (before && stat.mtimeNs === before.mtimeNs && Number(stat.size) === before.size)) throw new Error('stale or invalid capture artifact'); return { hash: `sha256:${createHash('sha256').update(await readFile(path)).digest('hex')}` }; }
async function verifiedArtifact(repo: string, task: any, checkId: string, expected: any[], recipe: any): Promise<boolean> {
  if (!Array.isArray(expected) || expected.length !== recipe.artifacts.length) return false;
  const seen = new Set<string>();
  for (const artifact of recipe.artifacts) {
    const evidence = expected.find((entry: any) => entry?.path === artifact.path);
    if (!evidence || seen.has(artifact.path) || typeof evidence.hash !== 'string') return false;
    seen.add(artifact.path);
    try { const actual = await freshArtifact(await outputPath(repo, task, checkId, artifact.path)); if (actual.hash !== evidence.hash) return false; } catch { return false; }
  }
  return true;
}
async function verifiedStatus(repo: string, task: any): Promise<boolean> {
  if (task.state !== 'accepted' || task.outcome !== 'verified' || !task.candidate_hash || await candidateHash({ repo, task }) !== task.candidate_hash) return false;
  try {
    const digest = authorizationDigest(task);
    const records = (await readFile(join(repo, '.omp/ui-delivery/evidence', `${task.task_id}.jsonl`), 'utf8')).split('\n').filter(Boolean).flatMap((line) => { try { return [JSON.parse(line)]; } catch { return []; } }).filter((evidence) => evidence.taskId === task.task_id && evidence.approvedDesignHash === task.design_revision && evidence.candidateRevision === task.candidate_revision && evidence.candidateHash === task.candidate_hash && evidence.modelRoute === task.model_route && evidence.authorizationDigest === digest);
    const latest = (operation: string, key: string, id: string) => {
      const start = records.map((record, index) => ({ record, index })).filter(({ record }) => record.operation === operation && record[key] === id && record.attemptPhase === 'started').at(-1);
      if (!start || typeof start.record.attemptId !== 'string') return undefined;
      return records.slice(start.index + 1).find((record) => record.attemptPhase === 'completed' && record.attemptId === start.record.attemptId);
    };
    if (!task.approved_check_recipes.every((recipe: any) => latest('ui_run_check', 'checkId', recipe.id)?.outcome === 'verified')) return false;
    for (const recipe of task.capture_recipes) { const completed = latest('ui_capture', 'recipeId', recipe.id); if (!completed || completed.outcome !== 'captured' || !await verifiedArtifact(repo, task, recipe.check_id, completed.artifacts, recipe)) return false; }
    return true;
  } catch { return false; }
}
async function resultSnapshot(path: string): Promise<{ mtimeNs: bigint; size: number } | undefined> { try { const stat = await lstat(path, { bigint: true }); return { mtimeNs: stat.mtimeNs, size: Number(stat.size) }; } catch { return undefined; } }
async function freshResult(path: string, before: { mtimeNs: bigint; size: number } | undefined): Promise<void> { const stat = await lstat(path, { bigint: true }); if (!stat.isFile() || stat.isSymbolicLink() || stat.nlink !== 1n || (before && before.mtimeNs === stat.mtimeNs && before.size === Number(stat.size))) throw new Error('stale check result'); if (!exactResult(JSON.parse(await readFile(path, 'utf8')))) throw new Error('check result is unverified'); }
async function updateTask(repo: string, taskFile: string, task: Record<string, unknown>, signal: AbortSignal): Promise<void> { if (signal.aborted) throw new Error('patch aborted'); const target = await resolveTaskFile({ repo, taskFile }); const temporary = join(dirname(target), `.${basename(target)}.${process.pid}.${Date.now()}.tmp`); await writeFile(temporary, JSON.stringify(task), { mode: 0o600, flag: 'wx' }); if (signal.aborted) { await writeFile(temporary, ''); throw new Error('patch aborted'); } await rename(temporary, target); }
function evidenceRecord(task: any, attemptId: string, attemptPhase: 'started' | 'completed', operation: string, selector: Record<string, string>, outcome: string, artifacts: unknown[], elapsedMs: number, checked?: any): Record<string, unknown> { return { taskId: task.task_id, approvedDesignHash: task.design_revision, candidateRevision: task.candidate_revision, candidateHash: task.candidate_hash, modelRoute: task.model_route, authorizationDigest: authorizationDigest(task), attemptId, attemptPhase, operation, ...selector, outcome, elapsedMs, artifacts, stdoutHash: checked?.stdout?.hash ?? 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', stderrHash: checked?.stderr?.hash ?? 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' }; }
async function appendAttempt(repo: string, task: any, record: Record<string, unknown>): Promise<void> { await appendEvidence({ repo, evidenceFile: join(repo, '.omp/ui-delivery/evidence', `${task.task_id}.jsonl`), record }); }

export function registerUiDeliveryPolicy(pi: ExtensionAPI, deps: { runCheck?: typeof defaultRunCheck } = {}): void {
  const checkRunner = deps.runCheck ?? defaultRunCheck; let stitch: { authorizationDigest: string; policy: StitchPolicy } | undefined;
  pi.registerTool({ name: 'ui_delivery_status', label: 'UI delivery status', description: 'Read bounded UI delivery task status.', parameters: pi.zod.object({ taskFile: pi.zod.string().optional() }).strict(), approval: 'read', strict: true, async execute(_id, params, _signal, _onUpdate, ctx) { const taskFile = (params as { taskFile?: string }).taskFile; if (!taskFile) return result(STATUS); const task = await loadTask({ repo: ctx.cwd, taskFile }); const digest = authorizationDigest(task); const approved = process.env.UI_DELIVERY_APPROVED_TASK_SHA256 === digest; const registry = pi.getAllTools?.() ?? []; if (approved && stitch?.authorizationDigest !== digest) stitch = { authorizationDigest: digest, policy: createStitchPolicy({ task, registry }) }; const verified = await verifiedStatus(ctx.cwd, task); return result({ extension: STATUS.extension, taskId: task.task_id, state: task.state, outcome: verified ? task.outcome : 'evidence_unverified', verified, authorizationDigest: digest, approved: approved && verified || approved && task.outcome === 'unverified' }); } });
  pi.registerTool({ name: 'ui_apply_patch', label: 'Apply approved UI patch', description: 'Apply an authorized non-destructive unified diff.', parameters: pi.zod.object({ taskFile: pi.zod.string(), patch: pi.zod.string() }).strict(), approval: 'write', strict: true, async execute(_id, params, signal, _onUpdate, ctx) { const args = params as { taskFile: string; patch: string }; const task = await loadTask({ repo: ctx.cwd, taskFile: args.taskFile, operation: 'patch' }); const started = performance.now(); const changedFiles = diffTargets(args.patch); for (const target of changedFiles) await authorizePath({ repo: ctx.cwd, task, path: target }); await gitApply(ctx.cwd, args.patch, signal); const hash = await candidateHash({ repo: ctx.cwd, task }); const updated = { ...task, state: 'candidate_ready', candidate_revision: `git:${hash.slice(7, 19)}`, candidate_hash: hash, outcome: 'unverified' }; await updateTask(ctx.cwd, args.taskFile, updated, signal); const evidenceFile = join(ctx.cwd, '.omp/ui-delivery/evidence', `${task.task_id}.jsonl`); await appendEvidence({ repo: ctx.cwd, evidenceFile, record: { taskId: task.task_id, approvedDesignHash: task.design_revision, candidateRevision: updated.candidate_revision, candidateHash: hash, modelRoute: task.model_route, operation: 'ui_apply_patch', outcome: 'mutation_unknown', elapsedMs: Math.max(0, Math.round(performance.now() - started)), artifacts: [], stdoutHash: `sha256:${createHash('sha256').update(args.patch).digest('hex')}`, stderrHash: `sha256:${createHash('sha256').update('').digest('hex')}` } }); return result({ taskId: task.task_id, operation: 'ui_apply_patch', state: updated.state, candidateRevision: updated.candidate_revision, candidateHash: hash, authorizationDigest: authorizationDigest(updated), evidenceRef: `artifact://${task.task_id}/evidence.jsonl`, changedFiles }); } });
  pi.registerTool({ name: 'ui_run_check', label: 'Run approved UI check', description: 'Run a named approved check in an OS sandbox.', parameters: pi.zod.object({ taskFile: pi.zod.string(), checkId: pi.zod.string() }).strict(), approval: 'exec', strict: true, async execute(_id, params, signal, _onUpdate, ctx) {
    const args = params as { taskFile: string; checkId: string }; const task = await loadTask({ repo: ctx.cwd, taskFile: args.taskFile, operation: 'check' }); const started = performance.now();
    if (!task.candidate_revision || !task.candidate_hash || await candidateHash({ repo: ctx.cwd, task }) !== task.candidate_hash) throw new Error('candidate hash does not match current worktree');
    const recipe = task.approved_check_recipes.find((entry: any) => entry.id === args.checkId); if (!recipe) throw new Error('unknown approved check');
    const path = await outputPath(ctx.cwd, task, args.checkId, recipe.result_path); const before = await resultSnapshot(path); const attemptId = randomUUID(); const selector = { checkId: args.checkId }; let checked: any;
    await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'started', 'ui_run_check', selector, 'pending', [], 0));
    try {
      checked = await checkRunner({ repo: ctx.cwd, task, checkId: args.checkId, signal }); if (checked.exitCode !== 0) throw new Error('check result is unverified'); await freshResult(path, before);
      if (await candidateHash({ repo: ctx.cwd, task }) !== task.candidate_hash) throw new Error('candidate changed');
      await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'completed', 'ui_run_check', selector, 'verified', [], Math.max(0, Math.round(performance.now() - started)), checked));
      return result({ taskId: task.task_id, operation: 'ui_run_check', checkId: args.checkId, exitCode: checked.exitCode, stdoutHash: checked.stdout.hash, stderrHash: checked.stderr.hash });
    } catch (error) {
      try { await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'completed', 'ui_run_check', selector, 'failed', [], Math.max(0, Math.round(performance.now() - started)), checked)); } catch {}
      throw error;
    }
  } });
  pi.registerTool({ name: 'ui_capture', label: 'Capture approved UI evidence', description: 'Record only artifacts named by an approved capture recipe.', parameters: pi.zod.object({ taskFile: pi.zod.string(), recipeId: pi.zod.string() }).strict(), approval: 'exec', strict: true, async execute(_id, params, signal, _onUpdate, ctx) {
    const args = params as { taskFile: string; recipeId: string }; const task = await loadTask({ repo: ctx.cwd, taskFile: args.taskFile, operation: 'capture' }); const started = performance.now();
    if (!task.candidate_revision || !task.candidate_hash || await candidateHash({ repo: ctx.cwd, task }) !== task.candidate_hash) throw new Error('candidate hash does not match current worktree');
    const recipe = task.capture_recipes.find((entry: any) => entry.id === args.recipeId); if (!recipe) throw new Error('unknown capture recipe'); const check = task.approved_check_recipes.find((entry: any) => entry.id === recipe.check_id); if (!check) throw new Error('unknown approved check');
    const resultPath = await outputPath(ctx.cwd, task, recipe.check_id, check.result_path); const resultBefore = await resultSnapshot(resultPath); const before = await Promise.all(recipe.artifacts.map(async (artifact: any) => resultSnapshot(await outputPath(ctx.cwd, task, recipe.check_id, artifact.path))));
    const attemptId = randomUUID(); const selector = { recipeId: args.recipeId }; let checked: any;
    await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'started', 'ui_capture', selector, 'pending', [], 0));
    try {
      checked = await checkRunner({ repo: ctx.cwd, task, checkId: recipe.check_id, signal }); if (checked.exitCode !== 0) throw new Error('capture check did not succeed'); await freshResult(resultPath, resultBefore);
      const artifacts = await Promise.all(recipe.artifacts.map(async (artifact: any, index: number) => ({ path: artifact.path, ...(await freshArtifact(await outputPath(ctx.cwd, task, recipe.check_id, artifact.path), before[index])) })));
      if (await candidateHash({ repo: ctx.cwd, task }) !== task.candidate_hash) throw new Error('candidate changed');
      await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'completed', 'ui_capture', selector, 'captured', artifacts, Math.max(0, Math.round(performance.now() - started)), checked));
      return result({ taskId: task.task_id, operation: 'ui_capture', artifacts: artifacts.map((artifact) => basename(artifact.path)) });
    } catch (error) {
      try { await appendAttempt(ctx.cwd, task, evidenceRecord(task, attemptId, 'completed', 'ui_capture', selector, 'failed', [], Math.max(0, Math.round(performance.now() - started)), checked)); } catch {}
      throw error;
    }
  } });
  const hookable = pi as unknown as { on?: (event: string, handler: (event: any) => Promise<unknown>) => void };
  hookable.on?.('tool_call', async (event) => { if (typeof event?.toolName !== 'string' || !event.toolName.startsWith('mcp__stitch__')) return undefined; try { if (!stitch) throw new Error('Stitch tool call is not authorized'); const input = event.input; const projectId = input && typeof input === 'object' && (typeof input.projectId === 'string' ? input.projectId : typeof input.project_id === 'string' ? input.project_id : undefined); if (!projectId) throw new Error('Stitch project binding is required'); await stitch.policy.authorize({ projectId, toolName: event.toolName, input }); return undefined; } catch (error) { return { block: true, reason: error instanceof Error ? error.message : 'Stitch tool call is not authorized' }; } });
  hookable.on?.('tool_result', async (event) => { if (!stitch || typeof event?.toolName !== 'string' || !event.toolName.startsWith('mcp__stitch__')) return undefined; if (stitch.policy.classify(event.toolName) === 'mutation' && event.isError) stitch.policy.recordDispatchFailed(); if (stitch.policy.classify(event.toolName) === 'read' && stitch.policy.state() === 'mutation_unknown') stitch.policy.recordReadback({ toolName: event.toolName, reconciled: !event.isError }); return undefined; });
}
export default function uiDeliveryPolicy(pi: ExtensionAPI): void { registerUiDeliveryPolicy(pi); }
