#!/usr/bin/env bats
# T022/FR-036/E9 — an independent tree hash, computed by something apm does not
# control, wired as a standing gate.
#
# The lockfile is generated by apm and `apm audit` reads it back. Alone, that is
# one party checking its own work: any bug in how apm records what it deployed is
# invisible to the only thing that would report it. This computes the hash with
# apm_hash_lib.sh — Manifest's own NUL-safe walk, which apm has no part in — and
# compares against what apm claims.
#
# T033/FR-016 rides along here because it is the same shape of assertion: assert
# the ABSENCE of a thing in the deployed tree, not merely that a code path was
# skipped. "The copy step wasn't invoked" is a statement about our code; "the
# file is not there" is a statement about the user's machine.

load '../test_helper/bats-support/load'
load '../test_helper/bats-assert/load'

REPO_ROOT="$BATS_TEST_DIRNAME/../.."
HASH_LIB="$REPO_ROOT/configs/claude/scripts/apm_hash_lib.sh"

setup() {
    export BATS_TMPDIR="${BATS_TMPDIR:-/tmp}"
    SANDBOX="$(mktemp -d "$BATS_TMPDIR/apm_indep_hash.XXXXXX")"
    export HOME="$SANDBOX/home"
    mkdir -p "$HOME/.claude/skills"

    # shellcheck disable=SC1090
    source "$HASH_LIB"
    # shellcheck disable=SC1090
    source "$REPO_ROOT/bootstrap/lib/common.sh"
    print_success() { :; }
    print_warning() { :; }
    print_error() { :; }
    print_info() { :; }
    print_step() { :; }

    SRC="$SANDBOX/src"
    for s in alpha beta; do
        mkdir -p "$SRC/$s"
        printf -- '---\nname: %s\ndescription: d\n---\nbody\n' "$s" > "$SRC/$s/SKILL.md"
    done
}

teardown() {
    [[ -n "$SANDBOX" && -d "$SANDBOX" ]] && rm -rf "$SANDBOX"
}

# --- T022: the hash is independent and it actually discriminates -------------

@test "the independent hash is stable for an unchanged tree" {
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null
    a="$(apm_canonical_tree_hash "$HOME/.claude/skills")"
    b="$(apm_canonical_tree_hash "$HOME/.claude/skills")"
    [ -n "$a" ]
    [ "$a" = "$b" ]
}

@test "the independent hash changes when a deployed file's CONTENT changes" {
    # The case apm cannot see at all: content drift inside a deployed file is not
    # one of its four drift categories, so this hash is the only thing that would
    # ever notice a hand-edit.
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null
    before="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    echo "hand edit" >> "$HOME/.claude/skills/alpha/SKILL.md"
    after="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    [ "$before" != "$after" ]
}

@test "the independent hash changes when a file is added" {
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null
    before="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    mkdir -p "$HOME/.claude/skills/orphan"
    echo "left behind" > "$HOME/.claude/skills/orphan/SKILL.md"
    after="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    [ "$before" != "$after" ]
}

@test "the independent hash changes when a file is removed" {
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null
    before="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    rm -rf "$HOME/.claude/skills/beta"
    after="$(apm_canonical_tree_hash "$HOME/.claude/skills")"

    [ "$before" != "$after" ]
}

@test "an identical tree at a different path hashes the same" {
    # Canonical means path-independent: the gate compares CONTENT, so a deploy
    # verified in a sandbox is still verified once it lands in a real home.
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null
    cp -R "$HOME/.claude/skills" "$SANDBOX/elsewhere"

    a="$(apm_canonical_tree_hash "$HOME/.claude/skills")"
    b="$(apm_canonical_tree_hash "$SANDBOX/elsewhere")"
    [ "$a" = "$b" ]
}

@test "the hash routine belongs to Manifest, not to apm" {
    # The independence claim, asserted rather than assumed: if this ever starts
    # shelling out to apm, the gate becomes apm checking its own work again.
    run grep -cE '(^|[^_[:alnum:]])apm (install|audit|list|pack)' "$HASH_LIB"
    assert_output "0"
}

# --- T033/FR-016: a disabled component is ABSENT, not merely un-copied -------

@test "a gated domain leaves NO files in the home, not just an unrun copy step" {
    export MANIFEST_APM_DOMAINS="$SANDBOX/domains.yml"
    printf 'domains:\n  - skills\n' > "$MANIFEST_APM_DOMAINS"

    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null

    # Absence on disk, not "the function returned early".
    run bash -c "find '$HOME/.claude/skills' -name SKILL.md 2>/dev/null | wc -l | tr -d ' '"
    assert_output "0"
}

@test "a domain excluded by the selector leaves NO files in the home" {
    MANIFEST_DEPLOY_DOMAINS="config" deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null

    run bash -c "find '$HOME/.claude/skills' -name SKILL.md 2>/dev/null | wc -l | tr -d ' '"
    assert_output "0"
}

@test "the absence assertions are not vacuous — the same call deploys when ungated" {
    # Without this, both tests above would pass against a deploy_home_skills that
    # never worked at all.
    deploy_home_skills "$SRC" "$HOME/.claude/skills" > /dev/null

    run bash -c "find '$HOME/.claude/skills' -name SKILL.md | wc -l | tr -d ' '"
    assert_output "2"
}
