#!/usr/bin/env bats
# Tests for bootstrap/lib/config.sh write_services_config

load '../test_helper/bats-support/load'
load '../test_helper/bats-assert/load'

REPO_ROOT="$BATS_TEST_DIRNAME/../.."

setup() {
    export BATS_TMPDIR="${BATS_TMPDIR:-/tmp}"
    SANDBOX=$(mktemp -d "$BATS_TMPDIR/bootstrap_services.XXXXXX")
    export SERVICES_CONFIG="$SANDBOX/config/services.yml"

    # Stub print helpers (defined in common.sh; config.sh calls them)
    print_step()    { :; }
    print_success() { :; }
    print_info()    { :; }
    print_warning() { :; }
    print_error()   { :; }

    # shellcheck disable=SC1090
    source "$REPO_ROOT/bootstrap/lib/config.sh"
}

teardown() {
    [[ -n "$SANDBOX" && -d "$SANDBOX" ]] && rm -rf "$SANDBOX"
}

@test "write_services_config emits antigravity section with enabled: false" {
    export ENABLE_CLAUDE=true ENABLE_GEMINI=true ENABLE_CURSOR=true ENABLE_CODEX=true
    export ENABLE_ANTIGRAVITY=false ENABLE_SKILLCLAW=false
    export ENABLE_GH=auto ENABLE_GLAB=auto

    run write_services_config
    assert_success

    grep -q "^  antigravity:" "$SERVICES_CONFIG"
    grep -A5 "^  antigravity:" "$SERVICES_CONFIG" | grep -q "enabled: false"
}

@test "write_services_config emits antigravity section with enabled: true" {
    export ENABLE_CLAUDE=true ENABLE_GEMINI=true ENABLE_CURSOR=true ENABLE_CODEX=true
    export ENABLE_ANTIGRAVITY=true ENABLE_SKILLCLAW=false
    export ENABLE_GH=auto ENABLE_GLAB=auto

    run write_services_config
    assert_success

    grep -q "^  antigravity:" "$SERVICES_CONFIG"
    grep -A5 "^  antigravity:" "$SERVICES_CONFIG" | grep -q "enabled: true"
}

@test "write_services_config emits graphify enabled: true by default" {
    set_bootstrap_defaults

    run write_services_config
    assert_success

    grep -q "^  graphify:" "$SERVICES_CONFIG"
    grep -A5 "^  graphify:" "$SERVICES_CONFIG" | grep -q "enabled: true"
}

@test "write_services_config emits graphify enabled: false when disabled" {
    set_bootstrap_defaults
    export ENABLE_GRAPHIFY=false

    run write_services_config
    assert_success

    grep -q "^  graphify:" "$SERVICES_CONFIG"
    grep -A5 "^  graphify:" "$SERVICES_CONFIG" | grep -q "enabled: false"
}

@test "load_existing_config keeps graphify disabled from file when no flag" {
    mkdir -p "$(dirname "$SERVICES_CONFIG")"
    cat > "$SERVICES_CONFIG" << 'YML'
services:
  graphify:
    enabled: false
YML
    set_bootstrap_defaults          # ENABLE_GRAPHIFY=true, GRAPHIFY_SET=false

    load_existing_config

    [ "$ENABLE_GRAPHIFY" = "false" ]
}

@test "explicit --enable-graphify wins over services.yml" {
    mkdir -p "$(dirname "$SERVICES_CONFIG")"
    cat > "$SERVICES_CONFIG" << 'YML'
services:
  graphify:
    enabled: false
YML
    set_bootstrap_defaults
    parse_bootstrap_args --enable-graphify   # GRAPHIFY_SET=true

    load_existing_config

    [ "$ENABLE_GRAPHIFY" = "true" ]
}

@test "committed services.yml matches write_services_config output with default toggles" {
    # Defaults per set_bootstrap_defaults() in config.sh — the committed copy is
    # deployed by rsync and read as the repo-side default by command_catalog.py,
    # so it must not drift from the generator (issue #460). The volatile
    # '# Generated by' date line is excluded on both sides.
    export ENABLE_CLAUDE=true ENABLE_GEMINI=true ENABLE_CURSOR=true ENABLE_CODEX=true
    export ENABLE_ANTIGRAVITY=true ENABLE_GRAPHIFY=true ENABLE_SKILLCLAW=false
    export ENABLE_BROWSER_USE=false ENABLE_SMOKE=false ENABLE_GH=auto ENABLE_GLAB=auto

    run write_services_config
    assert_success

    diff <(grep -v '^# Generated by' "$SERVICES_CONFIG") \
         <(grep -v '^# Generated by' "$REPO_ROOT/configs/claude/config/services.yml")
}
