#!/usr/bin/env bats
# docs_lint.py is the arbiter the docs-* skills defer to for "too long", so the
# things worth pinning are the ones a skill would silently get wrong: which cap
# applies to a file, what counts as over, and which files are exempt. A lint
# that mis-classifies is worse than no lint — it produces confident, wrong
# split instructions.

load '../test_helper/bats-support/load'
load '../test_helper/bats-assert/load'

setup() {
    REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)"
    LINT="$REPO_ROOT/plugins/manifest-docs/runtime/docs_lint.py"
    WORK="$BATS_TEST_TMPDIR/docs"
    mkdir -p "$WORK"
}

# Write $2 lines of filler markdown to $1.
make_doc() {
    local path="$1" lines="$2"
    mkdir -p "$(dirname "$path")"
    : > "$path"
    local i
    for ((i = 1; i <= lines; i++)); do
        printf 'line %d\n' "$i" >> "$path"
    done
}

run_lint() {
    cd "$WORK" || return 1
    run python3 -S -B "$LINT" "$@"
}

@test "a doc within its cap exits 0" {
    make_doc "$WORK/docs/SKILLCLAW.md" 50
    run_lint docs
    assert_success
    assert_output --partial "0 over cap"
}

@test "a doc over its cap exits 1 and names the overage" {
    make_doc "$WORK/docs/CONFIGURATION.md" 500
    run_lint docs
    assert_failure
    assert_output --partial "OVER (+100)"
    assert_output --partial "reference"
}

@test "classification is by path, not by size: a hub gets the 120-line cap" {
    make_doc "$WORK/docs/README.md" 200
    run_lint docs
    assert_failure
    assert_output --partial "hub"
    assert_output --partial "OVER (+80)"
}

@test "root README gets the readme_root cap, not the default" {
    make_doc "$WORK/README.md" 240
    run_lint README.md
    assert_failure
    assert_output --partial "readme_root"
    assert_output --partial "OVER (+40)"
}

@test "an unclassified doc falls back to the default cap" {
    make_doc "$WORK/docs/WHATEVER.md" 260
    run_lint docs
    assert_failure
    assert_output --partial "default"
    assert_output --partial "OVER (+10)"
}

@test "a doc-type override wins over the path classification" {
    make_doc "$WORK/docs/README.md" 200
    printf '<!-- doc-type: reference -->\n' >> "$WORK/docs/README.md"
    run_lint docs
    assert_success
    assert_output --partial "reference"
}

@test "an unknown doc-type is a hard failure, not a silent fallback" {
    make_doc "$WORK/docs/GUIDE.md" 10
    printf '<!-- doc-type: nonsense -->\n' >> "$WORK/docs/GUIDE.md"
    run_lint docs
    assert_failure
    assert_output --partial "unknown doc-type 'nonsense'"
}

@test "a doc-limit override with a rationale raises the cap" {
    make_doc "$WORK/docs/BIG.md" 300
    printf '<!-- doc-limit: 400 — one lookup table; splitting hides entries -->\n' \
        >> "$WORK/docs/BIG.md"
    run_lint docs
    assert_success
}

@test "a doc-limit override without a rationale fails" {
    # An opt-out nobody can evaluate is worse than no opt-out.
    make_doc "$WORK/docs/BIG.md" 300
    printf '<!-- doc-limit: 400 -->\n' >> "$WORK/docs/BIG.md"
    run_lint docs
    assert_failure
    assert_output --partial "no '— <rationale>'"
}

@test "a generated doc is skipped, not counted" {
    make_doc "$WORK/docs/API.md" 900
    printf '<!-- generated by tool; DO NOT EDIT -->\n' \
        | cat - "$WORK/docs/API.md" > "$WORK/docs/API.tmp"
    mv "$WORK/docs/API.tmp" "$WORK/docs/API.md"
    run_lint docs
    assert_success
    assert_output --partial "1 skipped"
}

@test "records (specs, plans) are exempt: rewriting one to fit would falsify it" {
    make_doc "$WORK/docs/superpowers/plans/2026-01-01-thing.md" 900
    make_doc "$WORK/docs/OK.md" 10
    run_lint docs
    assert_success
    refute_output --partial "2026-01-01-thing"
}

@test "fluff is advisory: hits are reported but never fail the run" {
    make_doc "$WORK/docs/OK.md" 10
    printf 'This is a comprehensive and powerful tool.\n' >> "$WORK/docs/OK.md"
    run_lint docs
    assert_success
    assert_output --partial 'fluff "comprehensive"'
    assert_output --partial 'fluff "powerful"'
}

@test "fluff inside a fenced code block is not flagged" {
    # Flagging quoted code trains people to ignore the report.
    make_doc "$WORK/docs/OK.md" 10
    {
        printf '```bash\n'
        printf 'echo "comprehensive"\n'
        printf '```\n'
    } >> "$WORK/docs/OK.md"
    run_lint docs
    assert_success
    refute_output --partial 'fluff "comprehensive"'
}

@test "a diagram page over max_diagrams fails even when under the line cap" {
    make_doc "$WORK/docs/ARCHITECTURE_DIAGRAMS.md" 40
    local i
    for ((i = 1; i <= 5; i++)); do
        {
            printf '```mermaid\n'
            printf 'flowchart LR\n  A --> B\n'
            printf '```\n'
        } >> "$WORK/docs/ARCHITECTURE_DIAGRAMS.md"
    done
    run_lint docs
    assert_failure
    assert_output --partial "5 diagrams (> 4)"
}

@test "--warn-only reports over-cap docs but exits 0" {
    make_doc "$WORK/docs/CONFIGURATION.md" 500
    run_lint docs --warn-only
    assert_success
    assert_output --partial "OVER"
}

@test "--json writes a machine-readable report" {
    make_doc "$WORK/docs/CONFIGURATION.md" 500
    run_lint docs --json "$BATS_TEST_TMPDIR/out.json" --quiet
    assert_failure
    run python3 -c "
import json, sys
d = json.load(open('$BATS_TEST_TMPDIR/out.json'))
r = [x for x in d['results'] if x['file'].endswith('CONFIGURATION.md')][0]
print(r['type'], r['lines'], r['cap'], r['status'])
"
    assert_output "reference 500 400 OVER"
}

@test "a missing path is a usage error (exit 2), not a silent pass" {
    run_lint no-such-dir
    [ "$status" -eq 2 ]
}

@test "glob matching keeps ** and * distinct" {
    # `**/docs/README.md` must not match `README.md` at the root — fnmatch's
    # `*`-crosses-slashes behaviour would exempt far more than intended.
    make_doc "$WORK/README.md" 150
    run_lint README.md
    assert_success
    assert_output --partial "readme_root"
}

@test "the repo's own concision reference stays within its cap" {
    cd "$REPO_ROOT" || return 1
    run python3 -S -B "$LINT" plugins/manifest-docs/runtime/references/doc-concision.md
    assert_success
}
